"""empty message

Revision ID: 181d9eb0dc5a
Revises: dfc6f2d6043b
Create Date: 2022-06-02 21:51:50.202611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181d9eb0dc5a'
down_revision = 'dfc6f2d6043b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('lieu', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'lieu')
    # ### end Alembic commands ###
