"""empty message

Revision ID: 19dde9b8236f
Revises: 
Create Date: 2022-06-07 15:10:56.414146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dde9b8236f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'sport')
    op.add_column('tips', sa.Column('url_pict', sa.String(), nullable=True))
    op.drop_column('tips', 'hours')
    op.drop_column('tips', 'pict')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tips', sa.Column('pict', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tips', sa.Column('hours', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tips', 'url_pict')
    op.add_column('event', sa.Column('sport', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
