"""empty message

Revision ID: 357158cc308d
Revises: 
Create Date: 2022-05-30 01:56:03.146482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357158cc308d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('img_url', sa.String(), nullable=True))
    op.drop_column('categories', 'url')
    op.drop_column('categories', 'img')
    op.add_column('users', sa.Column('sport', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lieux', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lieux')
    op.drop_column('users', 'sport')
    op.add_column('categories', sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'img_url')
    # ### end Alembic commands ###
