"""empty message

Revision ID: 3bc01cf108a3
Revises: b7b08c5d8161
Create Date: 2022-05-28 15:25:10.959164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc01cf108a3'
down_revision = 'b7b08c5d8161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sport', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lieux', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lieux')
    op.drop_column('users', 'sport')
    # ### end Alembic commands ###
