"""empty message

Revision ID: 421cbfe58f5d
Revises: dcdd0e689f8e
Create Date: 2022-06-02 20:02:41.983916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421cbfe58f5d'
down_revision = 'dcdd0e689f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'idCategorie')
    op.drop_column('event', 'pict')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('pict', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('idCategorie', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
