"""importall

Revision ID: 5f63b8d044de
Revises: e9d82f4c767e
Create Date: 2022-03-14 14:32:48.568858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f63b8d044de'
down_revision = 'e9d82f4c767e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
