"""User modify

Revision ID: 63407115f53a
Revises: b10c19fb4a2c
Create Date: 2022-04-29 14:55:17.345855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63407115f53a'
down_revision = 'b10c19fb4a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
