"""update models

Revision ID: 6671cb6cdb9d
Revises: 99a9e8f191c9
Create Date: 2022-05-17 11:35:23.306227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6671cb6cdb9d'
down_revision = '99a9e8f191c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
