"""empty message

Revision ID: 6fdc4615b01b
Revises: 3bc01cf108a3
Create Date: 2022-05-28 17:03:32.898941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fdc4615b01b'
down_revision = '3bc01cf108a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
