"""empty message

Revision ID: 733adbfe85da
Revises: f84dfb6a9b35
Create Date: 2022-06-07 22:26:53.628854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733adbfe85da'
down_revision = 'f84dfb6a9b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('sport', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'sport')
    # ### end Alembic commands ###
