"""try_again

Revision ID: 76a7b0a83e28
Revises: 5f63b8d044de
Create Date: 2022-03-14 14:43:01.080466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a7b0a83e28'
down_revision = '5f63b8d044de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcartegorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labelSubcategorie', sa.String(), nullable=True),
    sa.Column('descSubcategorie', sa.String(), nullable=True),
    sa.Column('idCategorie', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nbToken', sa.String(), nullable=True),
    sa.Column('idOwnUser', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('adress', sa.String(), nullable=True),
    sa.Column('dateRegister', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('postalCode', sa.Integer(), nullable=True),
    sa.Column('banqCardNumb', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('token')
    op.drop_table('subcartegorie')
    # ### end Alembic commands ###
