"""empty message

Revision ID: 78ec2930d0cd
Revises: 733adbfe85da
Create Date: 2022-06-08 21:09:53.341075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ec2930d0cd'
down_revision = '733adbfe85da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('adress', sa.String(), nullable=True))
    op.add_column('event', sa.Column('duree', sa.String(), nullable=True))
    op.drop_column('event', 'lieu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('lieu', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('event', 'duree')
    op.drop_column('event', 'adress')
    # ### end Alembic commands ###
