"""empty message

Revision ID: 88440610b837
Revises: 
Create Date: 2022-05-23 12:16:25.528860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88440610b837'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labelCategorie', sa.String(), nullable=True),
    sa.Column('descCategorie', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUsers', sa.String(), nullable=True),
    sa.Column('idMessages', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('idCategorie', sa.Integer(), nullable=True),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('pict', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcartegorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labelSubcategorie', sa.String(), nullable=True),
    sa.Column('descSubcategorie', sa.String(), nullable=True),
    sa.Column('idCategorie', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nbToken', sa.String(), nullable=True),
    sa.Column('idOwnUser', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('isadmin', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('postalCode', sa.Integer(), nullable=True),
    sa.Column('banqCardNumb', sa.Integer(), nullable=True),
    sa.Column('adress', sa.String(), nullable=True),
    sa.Column('dateRegister', sa.DateTime(), nullable=True),
    sa.Column('pict', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('idUser', sa.String(), nullable=True),
    sa.Column('idCategorie', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('users')
    op.drop_table('token')
    op.drop_table('subcartegorie')
    op.drop_table('message')
    op.drop_table('event')
    op.drop_table('conversation')
    op.drop_table('categories')
    # ### end Alembic commands ###
