"""empty message

Revision ID: 8c7a95cc1e42
Revises: ff98e912b74a
Create Date: 2022-05-27 22:06:25.296068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7a95cc1e42'
down_revision = 'ff98e912b74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sport', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lieux', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lieux')
    op.drop_column('users', 'sport')
    # ### end Alembic commands ###
