"""update models

Revision ID: 99a9e8f191c9
Revises: 
Create Date: 2022-05-17 10:49:02.604355

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '99a9e8f191c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('url', sqlalchemy_utils.types.url.URLType(), nullable=True))
    op.drop_column('categories', 'pict')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('pict', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'url')
    # ### end Alembic commands ###
