"""empty message

Revision ID: 9b0b77677041
Revises: 016a0e11cf6d
Create Date: 2022-06-07 09:50:20.945277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0b77677041'
down_revision = '016a0e11cf6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tips', sa.Column('hours', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tips', 'hours')
    # ### end Alembic commands ###
