"""empty message

Revision ID: a2706d17a17b
Revises: 88440610b837
Create Date: 2022-05-23 13:02:05.596169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2706d17a17b'
down_revision = '88440610b837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('iscoach', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'iscoach')
    # ### end Alembic commands ###
