"""empty message

Revision ID: a4a9abe31c3b
Revises: c50985926586
Create Date: 2022-06-02 12:52:52.495914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a9abe31c3b'
down_revision = 'c50985926586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tips', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('tips', 'tips')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tips', sa.Column('tips', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tips', 'content')
    # ### end Alembic commands ###
