"""update models

Revision ID: ad2a9c7092da
Revises: 6671cb6cdb9d
Create Date: 2022-05-17 11:38:08.762334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2a9c7092da'
down_revision = '6671cb6cdb9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
