"""empty message

Revision ID: b2593d5166e4
Revises: 
Create Date: 2022-06-01 12:37:58.085072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2593d5166e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.add_column('event', sa.Column('listOfParticipant', sa.String(), nullable=True))
    op.add_column('users', sa.Column('coin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'coin')
    op.drop_column('event', 'listOfParticipant')
    op.create_table('token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nbToken', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idOwnUser', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='token_pkey')
    )
    # ### end Alembic commands ###
