"""empty message

Revision ID: baf12c6a4072
Revises: 19dde9b8236f
Create Date: 2022-06-07 15:27:09.836848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf12c6a4072'
down_revision = '19dde9b8236f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('sport', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'sport')
    # ### end Alembic commands ###
