"""empty message

Revision ID: d31bc36fbacc
Revises: 
Create Date: 2022-05-23 14:53:35.856254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31bc36fbacc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('img', sa.String(), nullable=True))
    op.add_column('users', sa.Column('iscoach', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'iscoach')
    op.drop_column('categories', 'img')
    # ### end Alembic commands ###
