"""empty message

Revision ID: db847a7c027e
Revises: d31bc36fbacc
Create Date: 2022-05-26 18:30:56.004382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db847a7c027e'
down_revision = 'd31bc36fbacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('img_url', sa.String(), nullable=True))
    op.drop_column('categories', 'img')
    op.drop_column('categories', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'img_url')
    # ### end Alembic commands ###
