"""empty message

Revision ID: dcdd0e689f8e
Revises: a4a9abe31c3b
Create Date: 2022-06-02 12:52:57.723998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdd0e689f8e'
down_revision = 'a4a9abe31c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
