"""empty message

Revision ID: dfc6f2d6043b
Revises: 421cbfe58f5d
Create Date: 2022-06-02 20:53:12.004298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc6f2d6043b'
down_revision = '421cbfe58f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
