"""empty message

Revision ID: f84dfb6a9b35
Revises: 
Create Date: 2022-06-07 22:07:00.344875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84dfb6a9b35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('url_pict', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event', sa.Column('date', sa.String(), nullable=True))
    op.add_column('event', sa.Column('lieu', sa.String(), nullable=True))
    op.add_column('event', sa.Column('hours', sa.String(), nullable=True))
    op.add_column('event', sa.Column('listOfParticipant', sa.String(), nullable=True))
    op.drop_column('event', 'idCategorie')
    op.drop_column('event', 'pict')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('pict', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('idCategorie', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('event', 'listOfParticipant')
    op.drop_column('event', 'hours')
    op.drop_column('event', 'lieu')
    op.drop_column('event', 'date')
    op.drop_table('tips')
    # ### end Alembic commands ###
