"""empty message

Revision ID: f98a3859595f
Revises: 9b0b77677041
Create Date: 2022-06-07 10:01:50.853764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98a3859595f'
down_revision = '9b0b77677041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('hours', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'hours')
    # ### end Alembic commands ###
