"""empty message

Revision ID: ff98e912b74a
Revises: db847a7c027e
Create Date: 2022-05-27 14:22:43.640771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff98e912b74a'
down_revision = 'db847a7c027e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
