"""Change user again

Revision ID: ffd69ab0aff4
Revises: 900e049e7039
Create Date: 2022-04-27 10:35:00.818585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd69ab0aff4'
down_revision = '900e049e7039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isadmin', sa.Boolean(), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'isadmin')
    # ### end Alembic commands ###
